In [1]:
import requests
import pandas as pd

url_serie_inadimplencia = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.21082/dados?formato=json"

resposta_banco_central = requests.get(url_serie_inadimplencia, timeout=30)
dados_em_json = resposta_banco_central.json()

tabela_inadimplencia = pd.DataFrame(dados_em_json)
tabela_inadimplencia.head()

         data valor
0  01/03/2011  3.17
1  01/04/2011  3.24
2  01/05/2011  3.37
3  01/06/2011  3.32
4  01/07/2011  3.42

In [2]:
tabela_inadimplencia["data"] = pd.to_datetime(tabela_inadimplencia["data"], format="%d/%m/%Y")
tabela_inadimplencia["valor"] = pd.to_numeric(tabela_inadimplencia["valor"])

tabela_inadimplencia.info()

<class 'pandas.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    186 non-null    datetime64[us]
 1   valor   186 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 3.0 KB

In [3]:
tabela_inadimplencia.tail()

          data  valor
181 2026-04-01   4.64
182 2026-05-01   4.75
183 2026-06-01   4.58
184 2026-07-01   4.88
185 2026-08-01   5.04

In [4]:
import plotly.express as px

grafico_inadimplencia_total = px.line(
    tabela_inadimplencia,
    x="data",
    y="valor",
    title="Inadimplência total do crédito no Brasil (% da carteira)",
    labels={"data": "Mês", "valor": "Inadimplência (%)"},
)
grafico_inadimplencia_total.show()

In [5]:
import sys
sys.path.append("..")

from pipeline.baixar_series_banco_central import baixar_serie_banco_central

tabela_inadimplencia_total = baixar_serie_banco_central(21082)
tabela_inadimplencia_total.tail()

          data  valor  codigo_serie
181 2026-04-01   4.64         21082
182 2026-05-01   4.75         21082
183 2026-06-01   4.58         21082
184 2026-07-01   4.88         21082
185 2026-08-01   5.04         21082

In [6]:
from pipeline.baixar_series_banco_central import baixar_todas_as_series_banco_central

todas_as_series = baixar_todas_as_series_banco_central()

todas_as_series.groupby("nome_serie").agg(
    primeira_data=("data", "min"),
    ultima_data=("data", "max"),
    quantidade_de_linhas=("valor", "count"),
)

                              primeira_data ultima_data  quantidade_de_linhas
nome_serie
concessoes_credito_total         2011-03-01  2026-08-01                   186
inadimplencia_pessoa_fisica      2011-03-01  2026-08-01                   186
inadimplencia_pessoa_juridica    2011-03-01  2026-08-01                   186
inadimplencia_recursos_livres    2011-03-01  2026-08-01                   186
inadimplencia_total              2011-03-01  2026-08-01                   186
ipca_variacao_mensal             1980-01-01  2026-08-01                   560
juro_medio_credito_total         2011-03-01  2026-08-01                   186
selic_acumulada_no_mes           1986-08-01  2026-10-01                   483
taxa_desocupacao                 2012-03-01  2026-08-01                   174